### PR TITLE
Gpu dev

### PR DESCRIPTION
**Pull request by liruipeng**
GPU support. Cheers

### CODE REVIEW

**Comment by xinye83** [comment]
not related to the PR but any plan to port EVSL into AMD hardwares?

**Comment by liruipeng** [comment]
> not related to the PR but any plan to port EVSL into AMD hardwares?

Not at this point. Porting to AMD needs to write HIP, right?

**Comment by xinye83** [comment]
Need to hipify the custom cuda kernels. The AMD software stack is still under development, some BLAS and LAPACK routines are still missing.

**Comment by xyz8713** [comment]
I have reviewed this.

**Pull request merged**
